#!/usr/bin/env sh

# Layout BSP (tiling puro)
yabai -m config layout bsp

# CERO padding - ventanas pegadas a los bordes
yabai -m config top_padding    0
yabai -m config bottom_padding 0
yabai -m config left_padding   0
yabai -m config right_padding  0

# Gap mínimo entre ventanas (2-4px para distinguirlas)
yabai -m config window_gap     2

# Sin bordes ni sombras visuales
yabai -m config window_border off
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off

# Cada ventana nueva se divide el espacio disponible
yabai -m config window_placement second_child

# Split ratio balanceado
yabai -m config split_ratio 0.50

# Apps que NO van en tiling
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^RoundPie$" manage=off


echo "yabai ultra minimal loaded.."
