# ============================================
# ULTRAMINIMAL ZSHRC (No Oh-My-Zsh)
# ============================================

# Environment variables
export EDITOR="nvim"
export VISUAL="nvim"
export PAGER="less"
export PATH="$HOME/dotfiles/bin:$HOME/.local/share/nvim/mason/bin:$HOME/.opencode/bin:/opt/homebrew/bin:$PATH"

# Node version manager (fnm — Rust, <5ms init, .nvmrc compatible)
eval "$(fnm env --use-on-cd)"

# Completion system (include Homebrew completions)
fpath=(/opt/homebrew/share/zsh/site-functions $fpath)
autoload -Uz compinit && compinit -C
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'

# FZF-powered tab completion
source /opt/homebrew/share/fzf-tab/fzf-tab.zsh
zstyle ':fzf-tab:*' fzf-flags --height 40% --layout=reverse
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'eza -la --icons --git $realpath'
zstyle ':fzf-tab:complete:*:*' fzf-preview 'bat -n --color=always $realpath 2>/dev/null || eza -la --icons --git $realpath 2>/dev/null'

# Vi mode
bindkey -v
export KEYTIMEOUT=1

# FZF configuration (optimized for 27" monitor @ 1920x1080)
eval "$(fzf --zsh)"

# Shell history (atuin — SQLite, search by dir/exit code)
eval "$(atuin init zsh --disable-up-arrow)"

# Theme colors (auto-generated by `theme` command)
[[ -f ~/.local/state/theme/colors.zsh ]] && source ~/.local/state/theme/colors.zsh

FZF_BASE_OPTS="--height 60% --layout=reverse --border \
  --preview-window=right:50%:wrap \
  --bind=ctrl-p:toggle-preview \
  --bind=J:down,K:up \
  --bind=ctrl-j:preview-down,ctrl-k:preview-up \
  --bind=ctrl-d:preview-page-down,ctrl-u:preview-page-up"
export FZF_DEFAULT_OPTS="$FZF_BASE_OPTS ${FZF_THEME_COLORS:-}"
export FZF_CTRL_T_OPTS="--preview 'bat -n --color=always {} 2>/dev/null | head -100' --preview-window=right:50%:wrap --bind 'enter:execute(nvim {})+abort'"
export FZF_ALT_C_OPTS="--preview 'eza -la --icons --git {}' --preview-window=right:50%:wrap"
command -v fd > /dev/null && export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
command -v fd > /dev/null && export FZF_ALT_C_COMMAND='fd --type d --hidden --follow --exclude .git'

# Autosuggestions config (MUST be before loading plugin)
# ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE loaded from ~/.local/state/theme/colors.zsh
ZSH_AUTOSUGGEST_STRATEGY=(history completion)

# Standalone plugins (install with brew)
[ -f /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh ] && source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh
[ -f /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ] && source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Starship prompt
eval "$(starship init zsh)"

# Editor aliases
alias vim='nvim'
alias vi='nvim'
alias lg='lazygit'
alias zshrc='nvim ~/.zshrc'
alias zshreload='source ~/.zshrc'

# Modern ls with eza (icons + git status)
alias ls='eza --icons'
alias ll='eza -l --icons --git'
alias la='eza -la --icons --git'
alias lt='eza -la --icons --git --tree --level=2'

# Modern CLI replacements
alias cat='bat --paging=never'
alias catp='bat'  # with pager
alias grep='rg'
alias find='fd'
alias sed='sd'
alias dft='difft'

# FZF + bat integration
alias fzfbat='fzf --preview "bat -n --color=always {}"'
alias fzfnvim='nvim $(fzf --preview "bat -n --color=always {}")'

# Git aliases
alias gs='git status -sb' gp='git push' gl='git pull' gc='git clone'
alias glog='git log --oneline --graph --decorate'
alias gcm='git commit -m' ga='git add' gaa='git add .'

# Tmux aliases (minimal)
alias tl='tmux list-sessions'
alias ta='tmux attach -t'
alias td='tmux detach'
alias tk='tmux kill-session -t'

# Create new tmux session with optional name (defaults to date yyyymmdd)
tn() {
  local session_name="${1:-$(date +%Y%m%d)}"
  tmux new-session -s "$session_name"
}

# System utilities
alias flushdns='sudo dscacheutil -flushcache && sudo killall -HUP mDNSResponder'

# Focus mode (brown noise for concentration)
alias focus='nohup ffplay -nodisp -loglevel quiet -f lavfi -i "anoisesrc=c=brown" -volume 40 &>/dev/null &'
alias unfocus='pkill -f "ffplay.*anoisesrc"'

# Arrow keys for autosuggestions
bindkey '^[[C' forward-char      # Right arrow - accept full suggestion
bindkey '^[OC' forward-char      # Right arrow (alternate escape sequence)
bindkey '^[[1;5C' forward-word   # Ctrl+Right - accept word


# Zoxide (smart cd replacement)
eval "$(zoxide init zsh)"

# Yazi file manager (cd-on-exit wrapper)
[ -f ~/dotfiles/zsh/yazi-wrapper.sh ] && source ~/dotfiles/zsh/yazi-wrapper.sh


# nextdns-blocker shell completion
command -v nextdns-blocker > /dev/null && eval "$(_NEXTDNS_BLOCKER_COMPLETE=zsh_source nextdns-blocker)"
export PATH="/opt/homebrew/opt/php@8.2/bin:$PATH"
export PATH="/opt/homebrew/opt/php@8.2/sbin:$PATH"

# bun completions
[ -s "/Users/aristeoibarra/.bun/_bun" ] && source "/Users/aristeoibarra/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# Local binaries
export PATH="$HOME/.local/bin:$PATH"

# Deduplicate PATH (prevents bloat on repeated source — must be last)
typeset -U PATH

# Local secrets (API keys, tokens — never tracked by git)
[[ -f ~/.env.local ]] && source ~/.env.local
